replicaCount: 1
image:
  repository: oldentomato/tomato-board-web
  tag: "7fba969"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 3000
secrets:
  name: post-back-secrets
revisionHistoryLimit: 3
