replicaCount: 1
image:
  repository: oldentomato/tomato-board-api
  tag: sha-b48eae8
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8080
secrets:
  name: tomato-board-back-secrets
revisionHistoryLimit: 3
