nameOverride: tomato-studio-front
replicaCount: 1
revisionHistoryLimit: 3
image:
  repository: oldentomato/tomato-studio-web
  tag: "sha-5f4c467"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
  targetPort: 80
persistence:
  enabled: false
secret:
  enabled: false
