{{- if .Values.secret.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "service.secretName" . }}
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    {{- .Values.secret.encryptedData | toYaml | nindent 4 }}
  template:
    metadata:
      name: {{ include "service.secretName" . }}
      namespace: {{ .Release.Namespace }}
    type: Opaque
{{- end }}
