apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: post-back-secrets
  namespace: post-system
spec:
  encryptedData:
    GITHUB_PAT: AgAzx1M9mxbP7Pz8nNfnDX08h4sdaf+r+3FT//j71DZLqAakcrKbxCCj7Y2ZNUMNJzDGYsFU5kPkP1/Bm0ge1y56klNoN93SyVpUogNm1Vu8ff000+Z0Sfter/eBaNefM1kUFAFHJ3G2pLbxnCODu61EZ9FUzWt6rpqNSbnKkd72akAOUhRUrjx5hHFq+mWErGKnkDlIOqgrjYJQIGxF4KDDXNdijl7izS5Tn333UBiOdikeYmlaJxL8+YjKWxgRCjiK+q2MMc1lsZMgyWUUGTC9gKYhnfT6xddMHDpYiaCuw2JwOrEcn6pBFy4IO1Y42hCpXrZ8ZbLb+qy9e34itaQ47c/xaWTlq/9rMZ+9T2B0A2J4e8ZlPxbq0DN+Q4HZgEG65zy/haOwgvfg/G1PnppZTjJy6wbCqPzTOqch1dZPUz5aodwdb+qVvknNOB9/v4G+YZqtNaf3nSxF/2EV8Vkl5hJFiCuHmP2fN0MH0BgRK67ffoiJgqsePIK/1blmuHJFK/M5lm3vLosvXJPI3JhN3L8njt059HfVlEeB9tHCeRWMw6AMMmnmkP8XE4Z7xC6+6qx9p/ChscBhHwP5T1Or22hwGJ7kXxt0wbveh+ZdZwuS7bcqZ6d4urZ0PVL23mZqpMup01Kg7wGnoox6n/oncADYSJwds/cDc3TvfcyORRB7utlUPnAgnjrvax1uQtK8ZpMRNXDCUVLrfbF8c4yDoWHwttitWiyQc1aJHat+ae0Dgfw7w9hs
  template:
    metadata:
      creationTimestamp: null
      name: post-back-secrets
      namespace: post-system
    type: Opqaue

