apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: post-back-secrets
  namespace: post-system
spec:
  encryptedData:
    GITHUB_PAT: AgCjFcD38l3WnhYHFWAo/41hLFkKb5amAFRa7tfgIX9EuxGw4yl6nv9BSxtz1Af2Z6ECjrRvjLbVMYtQuVtKpgUrIQudXKUJUFNouHdYmkH2H99VLXEu8Khkfb6LpDC1DorII6dUAFfl8bx8BFfvErk1UkH/dYDK77RCXFpyK0j0+b2IWaFc5PdVmBC30KghqXdMZQBwfdgg4BlegvDrJQupbYZATlOlplP0Vf5I9YjAiSVgpdiXBlM4abgfEnCrY03a0xooB0rZVjLu2qxfpOhxD2uqutexPuiQioDRZTrds0ZS5dmbvMr42iR3yGWLt0HOnVoAtynVKJmMMR2gQe+toj6g8FzloMsbHoObE80yJ+GrlnTGKZ/Rc8ilRlsOwmyB3Rp1R216Z8NG9goIaxaZGs4j/nHEWOuJAQq740GatAFO8CC6XPyw0vTRI/SN93pUjRiWDaM0ZUPsAnyfwKQKtkQcyyK0cme4YiBbWg/hWZKw6ZxLjuxBaXwOBAX7FtFV2qWzMzmM5jNGzWNtsRPxMa0kbj9z1E0w8NfqZ/9m9X15E33XRN4GqQV4/kJXqjlSohlN3fhAnAd2N7khf1wnSLdRDfqw+qslnniViuMo4tk8/4e8bCM3qlCr8LhbGfRKYRr2fAGGo9JCbbstNsymWjZgBW23/lXjuq9EkEQP9rmZS52O/szFBNed/GkjkanvfHj4ErsxGMtndX937z04gFTbabMnsHc1qxqcACumvym73zM4WyG5
  template:
    metadata:
      creationTimestamp: null
      name: post-back-secrets
      namespace: post-system
    type: Opqaue

