apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: post-front-secrets
  namespace: post-system
spec:
  encryptedData:
    VITE_SERVER_API_BASE_URL: AgBkKXOiUsrsj1IAp66ipLyiJRDibp4xAIwypDlV/aviAP8lVMKCoBNbzM7zJ9Do3AbnIVEkvzmnpNxfAJSjC6CFUBHNUR061QAx7pXOHwzGnZTSTLqHZrPUooa2PyMbcncdmecNZXHjrdIY9DOTR6U/uaybELUzmOY5+TRXkspAvJbP4wKvK6EqW0+8hfjnJhwv6MWd1SaWBxoK3QLG+GE2lyyR2dgYNjUSouEkiJ27R6X1s6bZ3wvKdDIaVfeu/hrIdPGrU325bsnJRTkRf+Dn4Y6x4yDA3TRumh++3CeXo3suf4ZQyzP5TSJ2/xE7IUUlYV+eCYk4Y6FSok8pxOfqfdKz0a1/bgd/qATy2tCP8o4bkOKBV7R9oJKnDV2WjHcZc5udZyZHY0mH1hgUqzqhuyHGuREVYN7w/C/fO20gYV2v+9dbDNJodRbtw/G2Jiw2PKf6+H7l7DW4g8coQtj6zDQMLRrgQ2ROXMJIC7Sm1UP7fOZvKdwyURcxg+FzFK8PGtqk7MkdX/DGtnpRxogG2U5asTR31TAyrHDc/Psq/N5HyihIP7ZnAT9jLfjUMXcTiUNZyJCgsfhX1JAMpfvHRiD7pJW2es0RJM/exRe6mQ8d6VvRDpmwZ/AjJc7DRa7HAyO9L0YHmrrYA8OIBlct3LowbRp2iwuI7uHigapY1+IKh6GiRIOjAmVZIgQJ64z2Z2YOt297aBPc39MzOVzmpp+SL/kpzlgJ1JmeLZf3cDGrlXrfJw==
    VITE_STORAGE_KEY: AgB2IqSr2OPgo+8DUYuWV76jOGOXIWZxi7HUntCAIfZzLwYBpIgRhb0rLV6lq3C1qL9+N0sTbGjJscypus7vscOhxKHmBfCKUE7OPypjLbGsH8Eyv+p3F75AhAKQN37diCMbsGLFh2i3GRb16sRSLLZ0K5yPVZYNDvEF+Y83o/Cdos0F41LoaLK4qlmmSzIx3GXvD+WbjZRWePcO7tMwzyyN2QK+//HdcEeKQvfqd7NJpJAu+pRuZSoVyNQHcxQ+9sq7KZ9zNrUuvA5C18nHNE2p+RIiqxNYapq+zwshme5XDglkI93OWWnB1SJZwbeMJyYLS4/IJ+PX+3GpfwNUxuH9geMXqO+stRDfDg4JxtKCuz/k7jLPtb1GtyMdM+GZBkGQGJGLOQi4eHuehMJGrBLl3JauMhePzeRdW7WrkTbg86cfJjbD+wwKv4ssc/6dJciutmxyE+dJqiq/M5WdRiNCEkD+jC7ilU7BYBGWHWeK5em9aDOTKuq74TnZBjbWDW6UifNxOQeNLm9kSM8KbJj94TKC1PU1ITJHXU2TWq5NQpL5NRc9WhQQfkqEjofrbME3qBYzbzoLXeQJMj17AECC+H4jfsJP3EA8rgav6/5Iyxvs6Zdzfbkv1/xmDyNTFasB0YknfNGVNEOuP6c3QNNloULEEmIEZOhnqRFSNFhBqhj+vxTMkOa/l95jCnYmiKF7aMeZfCMS4DlOKfgCd6ew
  template:
    metadata:
      creationTimestamp: null
      name: post-front-secrets
      namespace: post-system
    type: Opqaue

