apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: post-front-secrets
  namespace: post-system
spec:
  encryptedData:
    VITE_SERVER_API_BASE_URL: AgCDoOUcyRa1CL2rrX0pi+Sy3ryE2l1iYdzo6aA+iBzi+TTZxn7AY9B2RMuj1o9fthP8m4wA98WOWFjbCcfdkPn2AN9kHidxaYyvLov+07MWEEduCpTGDEBECe3eVCDV+zXl/6FNqcmTrOWHMtgp/+04eMN/GwlE9jH24N9KwlaJfXoTQJXluBNJyrDTY7020zt8U0NChE1JEQgMRbkgsU2bwH/cbc9tj9CENyaUOU7qCpTHGQSxlSkG7mNdvYZou5SqJ0XIOBw1tz/JYQdl6FblfKnOtY1GNmcinFqDPLbnJ94dVKenWXTb40GVDyvBC2Ba4WPS+iObo5eewDt2jX4YwXXvNSSvf7tl60GWVMTDjzPp2PlIwYnS/4Cw/geOmwDcBIXywqM7opy3XTpDEDM2ekSw9Z+lZu+UjGXHKjTpaXHvssS+xRMmaPB1MoTx6JsJz4Nj0hLWxKwogHiIlDZ38EJKmO5C/tB71XUnOj9LiNT9TtKb9x8dqsjDYhh6jwJbSgZdosuifuCvDYRq0cUAy70RVD5awwokSl9dY2Zi6+HAQW6gnF3X7szGEKaPqGxKh2ycIrwDZbT/1D3ftsFSr4Iyd3ctI90nGhVQLNExkPvII7VMHfwiMk+fhpVeRv3d2cjb+WMEMJmS7bxK06LPiDuD4lSqIrdovgktXHswilaf7g6WsvORRoBlQQ9AbMEhuWENJckXoXQhnyw0KASidB49psL145nU8w5kXk1nJ+SqTg==
    VITE_STORAGE_KEY: AgBICzRLAyI9uQuPofbAbYX7yiqBYRx0Hf6J7c0Kv/gL3F7Ij0XQfi8jFe8E7qVTEddnPUK+jhwGdFsJGTNj2TpAhqsu8+x2K2TW1s73fk7Y0Z+9jnknSZEBCIyVXizzJwnv9Lb4QrS57XrHy0+B+vFjhagoff8g293xZLNpFdSHUAtGw/Jqfyn/XiX1/Wd86N+5KxrneG/4jCrdEwEsOw12zv7keLWt2KttlmhER2d5dHeWLJQkw4eeGm3nFhCAqRfkzxO1hRlMyI/5DmAhdoJg9Vd1n5rb1mH9TT/uWQF7fR2ccRl5J8nGYMbCTDPhwUsWKRrWIl5CIbWLQrwlyINNuvs7tAUtlvIr7f2VgvM051nmwGYWL5hqxrBHe4dPwUUTU106cb/FrUoxWqRjRGTckQp6sVrQgSD+j0aiIBX3H/zHimFtCUJcJSh46eN7cZcRA58U9yDQ9W9IaANh4izTq5uYA1tMxEU6vroMcRn3m/l5w4tsE+hrJVvs9wt9w5oov88Xxo74eldRpA8VeifNZDmD9pKeuKjl5YpKbKjT6yphjnzlsUrtb82SljV0/HXtYgKUV4AYVwD84ZDRVemQtuRAVjylyFNbwirgUkdNbDkcJfUMbGZYIIQw0Q/kT/yqm30avUHPlSBVXmmsn9nIbCbzyYHFtbJYxKrVGk2ySfo6WFKXJ1FIBv4CKMmqCaCVdyU7bRQ675ucvqeaVI94
  template:
    metadata:
      creationTimestamp: null
      name: post-front-secrets
      namespace: post-system
    type: Opqaue

