apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: post-front-secrets
  namespace: post-system
spec:
  encryptedData:
    VITE_SERVER_API_BASE_URL: AgA+uP322xNNWBwXyji5JQFrApkz2depNzOqoIqJr6Nm5qbS2XjpLOTMkEh7DQwixFGmWDcJGs5qbD97xcYnUyk6BOiHftEf5Go7s6JEb/za8FbsuS/Fv+yJznSt9lT0RHnZD6JCqSQQKVf4M4P1Bg5/uPCajXi+CpjH6DU6B+4aryuWv3F8UQKDkBuZYqEvNGQ5VHAFCJ70Gd2Q3Gr0+yrczib89Du8CeNXXs5SGr2a4+gct1w5DJKCslPaHHnpAPueGI/ZKFRmle1/CQeN72rC2nkVRAi92g1amwd12KjJaB3Id2sOsyWYCoiZjJ/mZdjCYNW0AeRxFzNi+e93KR4L7I0GssIKUlaFDZjply71A56izpE+NG17POKhlIWhx/qmCrd1kFgFGctdEtnUPjER8J0srVU+k1c4s8DKPUYv0D1+x+LIpXAIkAaQh+I0GXXUso3falRFIa7Du3P8kPzStKME8JTZNe3D4QBDtTrZ6bT71Q/DsVxO6aIXEZx7PZFr+rzgm/FfWTh+2HTnxMiEwkCUdHBc0DZKjuXEdkKrZsHjPBItV2xbolRQ0dTBcPwENkzHQjBIukLUXNCRbdi7EiUBByHx8GMJiGnmadJMOu1M5NWxmlF5zPQ207xjX1WoNpNzOu6tThJ3GHX4JjpUCGAwJjGSNjjsV6Ny0LOSbsS0lVso+pEobOzvezSeIEyMZx/j3oHcpgj+QqloUP0TfsZRFVRuMiaEOmYCYIc9
    VITE_STORAGE_KEY: AgBpOieNZQHoekC5J6kxqrOcU2ayn9QtyZuVozz7VjA/E/I7URW34IAVgulVR11Hyeh/AykBf179g53yaQxg/Ty5R3bUo1rplgOtIjGljRmmvC7jayNhyDjwl8WvlEBy3cF8W5LEDfz4mAQMXnc+oXbHIPXXyv7c6sAuJhfg9FxJf1jZDTLZ8ZMOHWHI/FtcHbzzfNn5yYvRphhTKzocyXSs6sZ00LNYeEPFceyHJkD8JAC2vE5PuWNsscfzI6nljMjP9KRrBb0gn0ADESOdCmqBnWKyyOLbA87BgxdKEHjbbTu0xQxErp6OHOHhIIQLkKrC+2U7RMYn1QPxvQGelP5M5GQ/tAaydi9nVR3Hw0tSe6lcHWrNWwqQCOOOfYi2v8QSDEFbT4DzbLtwb1GYeQmsnsvUy3w8pg5Z8LohRkzlvTuknkpDNCsZEA2mCW3rMAkYqRL3l0h3uWhurF4bGjHTM79tNBAdwraY6KYmXFgFIn6Sw76jcTo4LMavfGjyxq6hs6ORDFJrTYIJ35FDOy4rWY5kQ+kF3tdExdk5oPFJjRY6UccbZraoPOy0NJmK+2SuF5j4+MCrZ9hDtGPBWBesDNdpwB8lE22vzL7k2eZz8SMxJoGNuH0DNLEpFW6LXm94iKJryLQ9AlvvgfrG1SzwHEUJHCmK6vzmU2rI7twpikHGWPZ6hRU506NuttYvTeEGt12iqEAlVCFs26/pTilO
  template:
    metadata:
      creationTimestamp: null
      name: post-front-secrets
      namespace: post-system
    type: Opqaue

