apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: post-front-secrets
  namespace: post-system
spec:
  encryptedData:
    SERVER_API_BASE_URL: AgCOs5Kpg+PIycaIon3zNcPDGcaxPQMGMfUMT2ItFERsFaz9XRdZS0pQvBYG3vGret2+O+cg8DY6+8t4naJqtM4c+Zf1xv/bM+x3xoqcLMhjQ8CCyGg0tPr6wAEDqjPLcuN2A8ksIycPoVwla5Y/kuPR759rAscPPTSJt7x9lRrIfbYDeJ3lmdT1DF1R8sm0dVfgdTeEJruKIemAM/AYDT2MNUZyDiusf/ovk9XDau2uXfQuj+QOUapYWQupgQ+fUOV1s63NCjPbsyJPHdlasWXs7aAeQEg817v+p4Kmt/1ZUKoiYsv7cim22s17IgQnP1Z250m1iStg14QBjenTxrnVFsCwiaKXw2a8fdY1Zl6xgDBAhaAALJmnIIjg8g4mqV/0dtfZBnrN28LTobDymSwFTi/5y0kbHc51ITWrByzzeje1prg3IKWRKpMQXfe6w+i8QyrFM6zMh9hDw3pgkO17J8NWLQo4CEVx/oHRG8nwNN1R7wlLHmfedFB8KCR8vXIMe5/Yu0KhijtoGA+6d1wAMOX3WQDeGRQw4FRYhFgktm010uaqUDDgxiTf9xMejawt/XydBqw/rW+RCGBCV7m58BfB/GNaSqLBVm8XsnDdv8V7ftHsFBkqSnh9DDZfAZxJqQhdGuu9kJsn/QTAo+SI7zrWMFTXHHpOCI5BkD93y8DTbxloRdCTsr2QykPxqS8Q1GWQRpVzwr8s7qQMmbXfURgRW6uZJf2zDkyxRfQp
    STORAGE_KEY: AgAHThcRn74wGvjp7qPXemd5JCcEhRTLVP6e2V67s6eUUZRVzJylAyPgdwwzZTberHgPz1HCzniWMJx1pib3sohC42epmMFsdF8lR+/MpRE39kP2j60LQBoz5ibnI9AAfNTt3eKgpw64RLjeXK97CjsURn5fYqOyl3ky7cAn6BgtcSrrlgZH5fXThG/6DVTo/nZy2F0eA15DEM9ZxyflVBrR9aXJJKaH558UK2/CXG0R3Q43Gjuz2gDcBBMJbKWTEKh8MCUSXJdXm5QpSWUL+xvFbUhEooxbmyD0Db5nygYF99n5cG9GTzyTaIIsuMRx7x6kmuOc8nSLlxCyuwJKQ4nTE6s4DoDbrTd+H2JlCswZUxWRJYWM1wpaucFjyKIc0+HwEwBVEPieyF8WMqRVJk9GO9tMXrqbjmEWJko5d2t/zp1eQvzIqvegrR7QK7uwacHNiNtywcZh6d2FxKTSNa39V8yco2TVY1NTNrjxkfZNCEuIV7onXlvWKnU6saDsCvX0Axjpt6xxuJdvt5WvDw3/LBLzpQ9fEf3icO0fvkKWzJOcUSRXDIgqLHiNYMO1JTc7Tb/Ebjes2WYu+p8iXyx91fj5eCY6h0YENfXi7jdLZ9y+JuarR3mzwOKA7/6hRjhMrX/AwYOkPo3cHbBdDwBT6pXtdEz5u8wSm9UbftpLKVQb8Tk6MgWqpCU/sjO04M15N6Q3DkcSQjoITSeCWa7c
  template:
    metadata:
      creationTimestamp: null
      name: post-front-secrets
      namespace: post-system
    type: Opqaue

